app_key: "i55ok2oleogmh83"
app_secret: "6tqn4mr1ujihirf"
access_token: "r88pvbx3c72ovkld"
access_token_secret: "jirnup620fchoqq"
user_id: "339264287"
access_type: "app_folder"

# app_key: "i55ok2oleogmh83"
# app_secret: <%= ENV["APP_SECRET"] %>
# access_token: "23lbxnghy3j7w7yn"
# access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>
# user_id: "339264287"
# access_type: "app_folder"